Repository algosup/2023-2024-project-2-x86-retrogaming-team-4, pull requests merged in 2023-12, with the labels that each got.

#30 Merge Ghost movments to dev branch
  .gitignore
  src/_test_sprites.asm
  src/build-pacman.cmd
  src/constants.asm
  src/entry.asm
  src/heapLibrary.inc
  src/initialization.asm
  src/main.asm
  src/move_sprites.asm
  src/sprites.asm
Labels: Dev

#66 Pellet eating editing
  src/collider.asm
  src/constants.asm
  src/interraction.asm
  src/main.asm
  src/maze.asm
  src/move_sprites.asm
  src/sprites.asm
Labels: Dev

#68 Keybuffer
  src/keyboard.asm
Labels: Dev

#71 Pellet eating correction
  src/buffers.asm
  src/collider.asm
  src/constants.asm
  src/interraction.asm
  src/keyboard.asm
  src/main.asm
  src/maze.asm
  src/move_sprites.asm
  src/sprites.asm
Labels: bug, Dev

#69 Merge dev to main
  .gitignore
  src/Initialization.asm
  src/buffers.asm
  src/collider.asm
  src/constants.asm
  src/entry.asm
  src/heapLibrary.inc
  src/initialization.asm
  src/interraction.asm
  src/keyboard.asm
  src/main.asm
  src/maze.asm
  src/move_sprites.asm
  src/sprites.asm
Labels: Dev

#75 Add Fruits
  src/constants.asm
  src/initialization.asm
  src/interraction.asm
  src/main.asm
  src/maze.asm
  src/sprites.asm
Labels: Dev

#76 Increment lives
  src/collider.asm
  src/constants.asm
  src/interraction.asm
  src/main.asm
  src/sprites.asm
Labels: Dev

#83 Fix the pacman's death and the stop of the fright time
  src/collider.asm
  src/main.asm
Labels: bug, Dev

#81 Win lose
  src/collider.asm
  src/initialization.asm
  src/interraction.asm
  src/main.asm
  src/maze.asm
  src/sprites.asm
Labels: Dev

#84 Score display
  src/collider.asm
  src/interraction.asm
  src/main.asm
  src/maze.asm
  src/sprites.asm
Labels: Dev

#85 Correction for collisions and teleporters
  src/collider.asm
  src/constants.asm
  src/interraction.asm
  src/keyboard.asm
  src/main.asm
  src/move_sprites.asm
Labels: bug, Dev

#87 Add fruit display mechanic
  src/constants.asm
  src/interraction.asm
  src/main.asm
Labels: Dev, Low

#88 Fix reset maze without the score and lives
  src/buffers.asm
  src/constants.asm
  src/initialization.asm
  src/interraction.asm
  src/main.asm
  src/maze.asm
  src/sprites.asm
Labels: bug, Dev, Low

#90 Fix several problems with the score, pellets, display and next level
  src/interraction.asm
  src/main.asm
Labels: bug, Dev, Medium

#91 Kill streak
  src/collider.asm
  src/interraction.asm
Labels: Dev

#86 Changed the strategy for ghost collision
  src/collider.asm
  src/constants.asm
Labels: Dev, Low

#93 unified all the sprites' speeds with a constant
  src/constants.asm
  src/keyboard.asm
Labels: Dev, Low
